name: Pull dots

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull dots
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WEBSERVER_IP }}
          username: ${{ secrets.WEBSERVER_USER }}
          key: ${{ secrets.WEBSERVER_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.WEBSERVER_SSH_PASSPHRASE }}
          script: |
            cd ~/dots/
            git pull
